# Configuración de Prometheus para Motogo Backend
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'motogo'
    environment: 'local'

# Habilitar Remote Write Receiver (para k6)
storage:
  tsdb:
    out_of_order_time_window: 30m

# Configuración de scraping
scrape_configs:
  # Monitoreo de Prometheus mismo
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Monitoreo del Backend Motogo
  - job_name: "motogo-backend"
    metrics_path: '/metrics'
    static_configs:
      - targets: ["host.docker.internal:8085"]

  # Monitoreo de Grafana
  - job_name: "grafana"
    metrics_path: '/metrics'
    static_configs:
      - targets: ["motogo-grafana:3000"]

  # Monitoreo de K6 a través de Pushgateway
  - job_name: "k6"
    honor_labels: true
    static_configs:
      - targets: ["motogo-pushgateway:9091"]
