repos:
  - repo: local
    hooks:
      - id: go-mod-tidy
        name: Go Mod Tidy
        entry: go mod tidy
        language: system
        types: [go]
        pass_filenames: false
      - id: go-mod-download
        name: Go Mod Download
        entry: go mod download
        language: system
        types: [go]
        pass_filenames: false

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.55.2  
    hooks:
      - id: golangci-lint
        name: GolangCI-Lint
        entry: golangci-lint run
        language: system
        types: [go]