package server

import (
	"log/slog"

	"github.com/gin-gonic/gin"
	"github.com/prometheus/client_golang/prometheus/promhttp"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	"github.com/EstebanGitPro/motogo-backend/cmd/dependency"
	"github.com/EstebanGitPro/motogo-backend/handlers"
	"github.com/EstebanGitPro/motogo-backend/middleware"
	"github.com/EstebanGitPro/motogo-backend/platform/logger"
	"github.com/EstebanGitPro/motogo-backend/platform/schema"
	_ "github.com/EstebanGitPro/motogo-backend/platform/swaggo" // docs generated by Swag CLI
)

func routing(app *gin.Engine, dependencies *dependency.Dependencies) {
	dependencies.Logger.Info(logger.LogRouteConfiguring)

	// Prometheus metrics endpoint (must be before other middleware)
	app.GET("/metrics", gin.WrapH(promhttp.Handler()))

	// Swagger documentation endpoint
	app.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Apply Prometheus metrics tracking middleware
	app.Use(middleware.TrackMetrics())

	errorHandler := middleware.NewErrorHandler(dependencies.MessagingCache, dependencies.Logger)
	app.Use(errorHandler.Handle())

	handler := handlers.New(dependencies.PersonService, dependencies.Interactor, dependencies.MessageInteractor, dependencies.MessagingCache, dependencies.Logger, dependencies.IDEncoder, dependencies.ResponseHandler)

	validators, err := schema.NewValidator(&schema.DefaultFileReader{})
	if err != nil {
		dependencies.Logger.Error(logger.LogRouteValidatorError, "error", err)
		dependencies.Logger.Fatal(logger.LogRouteValidatorError, "error", err)
	}
	dependencies.Logger.Success(logger.LogRouteValidatorOK)
	validator := middleware.NewMiddlewareValidator(validators, dependencies.Logger)

	// Richardson Maturity Model Nivel 2-3: Recursos con URIs únicas + HATEOAS
	public := app.Group("motogo/api/v1")
	{
		// === ACCOUNTS ENDPOINTS ===
		// POST /accounts - Crear nueva cuenta
		// Devuelve: 201 Created + Location header + HATEOAS links
		public.POST("/accounts", validator.WithValidateRegister(), handler.RegisterPerson())

		// GET /accounts/:id - Locate: Obtener cuenta por ID
		// Este es el endpoint referenciado en el Location header del POST
		//public.GET("/accounts/:id", handler.GetPersonByID())

		//public.POST("/auth/login", handler.Login())
		//public.GET("/accounts/email/:email", handler.GetPersonByEmail())

		// === MESSAGES ENDPOINTS (system administration) ===
		// POST /messages - Crear nuevo mensaje del sistema
		public.POST("/messages", validator.WithValidateMessage(), handler.CreateMessage())

		// PUT /messages/:id - Actualizar mensaje existente
		public.PUT("/messages/:id", validator.WithValidateMessage(), handler.UpdateMessage())

		// DELETE /messages/:id - Eliminar mensaje
		public.DELETE("/messages/:id", handler.DeleteMessage())

		// GET /messages/:id - Obtener mensaje por ID
		public.GET("/messages/:id", handler.GetMessageByID())

		// GET /messages - Listar mensajes (con filtros opcionales)
		// Query params: ?module=users&type=ERROR&category=usuario_final&active=true
		public.GET("/messages", handler.ListMessages())

		// POST /messages/cache/reload - Recargar caché de mensajes desde BD
		// Endpoint administrativo para forzar recarga después de cambios manuales
		public.POST("/messages/cache/reload", handler.ReloadMessageCache())
	}

	dependencies.Logger.Success(logger.LogRouteConfigured)
}

func Boostrap(app *gin.Engine) *dependency.Dependencies {
	dependencies, err := dependency.Init()
	if err != nil {
		slog.Error("Failed to initialize dependencies", slog.String("error", err.Error()))
		panic(err)
	}

	routing(app, dependencies)

	return dependencies
}
