package services_test

import (
	"context"
	"errors"
	"testing"

	"github.com/EstebanGitPro/motogo-backend/core/interactor/services"
	"github.com/EstebanGitPro/motogo-backend/core/interactor/services/domain"
	"github.com/EstebanGitPro/motogo-backend/mocks"
	"github.com/Nerzal/gocloak/v13"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
)

// TestResetPasswordWithToken_Success tests successful password reset flow
func TestResetPasswordWithToken_Success(t *testing.T) {
	// Arrange
	ctx := context.Background()
	mockRepo := new(mocks.MockRepository)
	mockAuthClient := new(mocks.MockAuthClient)
	mockLogger := new(mocks.MockLogger)

	service := services.NewService(mockRepo, mockAuthClient, mockLogger)

	// Valid JWT token (simulated - in real scenario would be generated by Keycloak)
	token := "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20ifQ.xyz"
	newPassword := "NewSecurePassword123"
	email := "test@example.com"
	userID := "kc-user-123"

	keycloakUser := &gocloak.User{
		ID:    &userID,
		Email: &email,
	}

	// Mock expectations
	mockLogger.On("Info", mock.Anything, mock.Anything).Return()
	mockLogger.On("Debug", mock.Anything, mock.Anything).Return()
	mockLogger.On("Success", mock.Anything, mock.Anything).Return()

	// GetUserByEmail should be called by the service
	mockAuthClient.On("GetUserByEmail", ctx, email).Return(keycloakUser, nil)

	// SetPassword should be called with temporary=false
	mockAuthClient.On("SetPassword", ctx, userID, newPassword, false).Return(nil)

	// Act
	err := service.ResetPasswordWithToken(ctx, token, newPassword)

	// Assert
	assert.NoError(t, err)

	mockAuthClient.AssertExpectations(t)
	mockLogger.AssertExpectations(t)
}

// TestResetPasswordWithToken_InvalidToken tests error when token is invalid
func TestResetPasswordWithToken_InvalidToken(t *testing.T) {
	// Arrange
	ctx := context.Background()
	mockRepo := new(mocks.MockRepository)
	mockAuthClient := new(mocks.MockAuthClient)
	mockLogger := new(mocks.MockLogger)

	service := services.NewService(mockRepo, mockAuthClient, mockLogger)

	// Invalid token
	invalidToken := "invalid-token-format"
	newPassword := "NewSecurePassword123"

	// Mock expectations
	mockLogger.On("Info", mock.Anything, mock.Anything).Return()
	mockLogger.On("Error", mock.Anything, mock.Anything).Return()

	// Act
	err := service.ResetPasswordWithToken(ctx, invalidToken, newPassword)

	// Assert
	assert.Error(t, err)
	assert.Equal(t, domain.ErrInvalidToken, err)

	mockLogger.AssertExpectations(t)
}

// TestResetPasswordWithToken_UserNotFound tests error when user email from token doesn't exist in Keycloak
func TestResetPasswordWithToken_UserNotFound(t *testing.T) {
	// Arrange
	ctx := context.Background()
	mockRepo := new(mocks.MockRepository)
	mockAuthClient := new(mocks.MockAuthClient)
	mockLogger := new(mocks.MockLogger)

	service := services.NewService(mockRepo, mockAuthClient, mockLogger)

	token := "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5vdGZvdW5kQGV4YW1wbGUuY29tIn0.xyz"
	newPassword := "NewSecurePassword123"
	email := "notfound@example.com"

	keycloakError := errors.New("user not found")

	// Mock expectations
	mockLogger.On("Info", mock.Anything, mock.Anything).Return()
	mockLogger.On("Debug", mock.Anything, mock.Anything).Return()
	mockLogger.On("Error", mock.Anything, mock.Anything).Return()

	mockAuthClient.On("GetUserByEmail", ctx, email).Return(nil, keycloakError)

	// Act
	err := service.ResetPasswordWithToken(ctx, token, newPassword)

	// Assert
	assert.Error(t, err)
	assert.Equal(t, domain.ErrUserNotFound, err)

	mockAuthClient.AssertExpectations(t)
	mockLogger.AssertExpectations(t)
}

// TestResetPasswordWithToken_SetPasswordFails tests error when Keycloak fails to update password
func TestResetPasswordWithToken_SetPasswordFails(t *testing.T) {
	// Arrange
	ctx := context.Background()
	mockRepo := new(mocks.MockRepository)
	mockAuthClient := new(mocks.MockAuthClient)
	mockLogger := new(mocks.MockLogger)

	service := services.NewService(mockRepo, mockAuthClient, mockLogger)

	token := "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20ifQ.xyz"
	newPassword := "NewSecurePassword123"
	email := "test@example.com"
	userID := "kc-user-123"

	keycloakUser := &gocloak.User{
		ID:    &userID,
		Email: &email,
	}

	keycloakError := errors.New("failed to update password in Keycloak")

	// Mock expectations
	mockLogger.On("Info", mock.Anything, mock.Anything).Return()
	mockLogger.On("Debug", mock.Anything, mock.Anything).Return()
	mockLogger.On("Error", mock.Anything, mock.Anything).Return()

	mockAuthClient.On("GetUserByEmail", ctx, email).Return(keycloakUser, nil)
	mockAuthClient.On("SetPassword", ctx, userID, newPassword, false).Return(keycloakError)

	// Act
	err := service.ResetPasswordWithToken(ctx, token, newPassword)

	// Assert
	assert.Error(t, err)
	assert.Equal(t, domain.ErrPasswordUpdateFailed, err)

	mockAuthClient.AssertExpectations(t)
	mockLogger.AssertExpectations(t)
}

// TestResetPasswordWithToken_EmptyToken tests error with empty token
func TestResetPasswordWithToken_EmptyToken(t *testing.T) {
	// Arrange
	ctx := context.Background()
	mockRepo := new(mocks.MockRepository)
	mockAuthClient := new(mocks.MockAuthClient)
	mockLogger := new(mocks.MockLogger)

	service := services.NewService(mockRepo, mockAuthClient, mockLogger)

	emptyToken := ""
	newPassword := "NewSecurePassword123"

	// Mock expectations
	mockLogger.On("Info", mock.Anything, mock.Anything).Return()
	mockLogger.On("Error", mock.Anything, mock.Anything).Return()

	// Act
	err := service.ResetPasswordWithToken(ctx, emptyToken, newPassword)

	// Assert
	assert.Error(t, err)
	assert.Equal(t, domain.ErrInvalidToken, err)

	mockLogger.AssertExpectations(t)
}
